import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { StatusBadge } from "@/components/logiflow/ui-kit"
import { supportTickets } from "@/lib/logiflow-data"
import { Plus } from "lucide-react"

export default function SupportPage() {
  return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-sm font-semibold uppercase tracking-wide text-primary">Exceptions</div><h1 className="mt-1 text-3xl font-bold tracking-tight">Support Issues</h1><p className="text-muted-foreground">Track delayed delivery, wrong address, damaged parcel, payment issues, customer complaints, and failed pickups.</p></div><Button><Plus className="mr-2 h-4 w-4" />Create issue</Button></div><div className="grid gap-4 md:grid-cols-4">{["Open","In Review","Resolved","Escalated"].map(item=><Card key={item}><CardHeader><CardTitle className="text-sm">{item}</CardTitle></CardHeader><CardContent className="text-2xl font-bold">{supportTickets.filter(t=>t.status===item).length}</CardContent></Card>)}</div><Card className="bg-white"><CardContent className="table-scroll p-0"><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Ticket ID</TableHead><TableHead>Shipment ID</TableHead><TableHead>Issue Type</TableHead><TableHead>Priority</TableHead><TableHead>Assigned Staff</TableHead><TableHead>Status</TableHead><TableHead>Notes</TableHead></TableRow></TableHeader><TableBody>{supportTickets.map(ticket=><TableRow key={ticket.ticketId} className="hover:bg-slate-50"><TableCell className="font-semibold text-primary">{ticket.ticketId}</TableCell><TableCell>{ticket.shipmentId}</TableCell><TableCell>{ticket.issueType}</TableCell><TableCell><StatusBadge value={ticket.priority} /></TableCell><TableCell>{ticket.assignedStaff}</TableCell><TableCell><StatusBadge value={ticket.status} /></TableCell><TableCell className="max-w-md text-sm text-muted-foreground">{ticket.notes}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>
}
